export interface ICondominio {
  id: number
  nome: string
  endereco: string
  bairro: string
  cidade: string
  estado: string
  tipo: string
  qtd_apartamento?: number
  qtd_bloco?: number
  garagem?: string
  qtd_vaga?: number
  sindico?: string
  telefone_sindico?: string
  email_sindico?: string
  telefone_condominio: string
  email_condominio: string
  administradora?: string
  telefone_administradora?: string
  email_administradora?: string
  seguranca?: string
  telefone_seguranca?: string
  email_seguranca?: string
  servicos_gerais?: string
  telefone_servicos_gerais?: string
  email_servicos_gerais?: string
  observacao?: string
  data_criacao: string
  data_edicao?: string
}
